apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ .Values.container.name }}
    name: {{ .Values.container.name }}-{{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.container.name }}
  ports:
  - name: http
    nodePort: {{ .Values.container.nodePort }}
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
