apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}-{{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        tier: {{ .Values.tier }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        resources:
          requests:
            cpu: {{ .Values.container.cpu }} 
            memory: {{ .Values.container.memory }} 
        ports:
        - containerPort: {{ .Values.container.port }}
