apiVersion: v1
kind: Service
metadata:
    labels:
        app: customer-service
    name: customer-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
  - name: http
    nodePort: 30007
    port: 6111
    targetPort: 6111
    protocol: TCP
