apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: registration-service
  kube-monkey/enabled: enabled
  kube-monkey/identifier: registration-service
  kube-monkey/mtbf: '1'
  kube-monkey/kill-mode: "fixed-percent"
  kube-monkey/kill-value: '30'
spec:
  selector:
    matchLabels:
      app: registration-service
  replicas: 3
  template:
    metadata:
      labels:
        app: registration-service
        tier: backend
        kube-monkey/enabled: enabled
        kube-monkey/identifier: registration-service
        kube-monkey/mtbf: '1'
        kube-monkey/kill-mode: "fixed-percent"
        kube-monkey/kill-value: '30'
    spec:
      containers:
      - name: registration-service
        image: colinbut/registration-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6111
