apiVersion: v1
kind: Service
metadata:
    labels:
        app: registration-service
    name: registration-service
spec:
  type: NodePort
  selector:
    app: registration-service
  ports:
  - name: http
    nodePort: 30008
    port: 6111
    targetPort: 6111
    protocol: TCP
