apiVersion: v1
kind: Service
metadata:
    labels:
        app: spring-boot-admin
    name: spring-boot-admin
spec:
  type: NodePort
  selector:
    app: spring-boot-admin
  ports:
  - name: http
    nodePort: 30007
    port: 6110
    targetPort: 6110
    protocol: TCP
